oliver006/redis_exporter

README.md, redis_exporter.go, redis_exporter_test.go
Adds the `redis.password` flag, which allows for authenticating connections to the Redis server or servers. To simplify the function signatures, a `RedisHost` structure was implemented to contain all information about the connection to Redis.
There weren't any test instructions, so I wasn't entirely sure how to proceed there, but I updated the portions of the test which used the `NewRedisExporter` to use the new `RedisHost` style. If you have any guidance on that I'll be happy to implement some tests for the authentication portions.
=> Add support for authentication

redis_exporter.go
This small change adds support for much older versions of redis which do not have TTL lines in the keys field. I've tested it with our old redis 2.4.15 installs and it works fine with this change.
=> Support older versions of redis which do not have key ttl per DB

exporter/redis.go, exporter/redis_test.go, main.go
I'd like to be able to export redis stats without having to run an additional binary.
=> Move redis exporter to a package

exporter/redis.go, main.go
I have the use case where I have several Redis instances on one machine, each of them with separate passwords. The existing redis_exporter didn't support different passwords for different Redis instances yet, so I extended it by splitting up the redis.password flag just like redis.addr has been split up previously.
=> Support separate per-instance password when monitoring more than one Redis instance

exporter/redis.go, exporter/redis_test.go, main.go
Fixes #20 
- moved validation of `-redis.addr` into `NewRedisExporter()` so that it is easier to test
- added test cases
@oliver006 let me know what you think, happy to adapt to your feedback
=> improve validation of -redis.addr

exporter/redis.go, exporter/redis_test.go
Counters should end with _total.
Units should be specified where known.
Group related metrics together.
Remove machine-level metrics, they should come from the node exporter.
Remove calculated rates, they should be calculated in Prometheus.
Convert units to seconds where possible.
=> Improve metrics in line with best practices.

README.md, main.go
Hi,
Thank you for the great exporter for Redis!
It it okay to change so that we can overwrite `redis.addr` (like `redis.password`) with an environment variable?
We already set redis address consumable as an environment variable from any docker containers with Kubernetes, so we want just pass it to this exporter too, instead of hard coding an address in a flag.
I added a very small func to deal with the default value. Let me know if it's a problem.
=> support REDIS_ADDR environment variable

exporter/redis.go
Closes https://github.com/oliver006/redis_exporter/issues/39
The implementation is straightforward: set redis_up to 0 before the connection is established (so any connection problems error will produce redis_up = 0) and set to 1 once any metric is fetched from redis server.
=> Add redis_up gauge

grafana_prometheus_redis_dashboard.json
Believe it or not, I had a redis instance with no connected clients, so the templating failed.
`redis_up` is probably a more "robust" choice.
=> Use `redis_up` for templating

README.md, exporter/redis.go, exporter/redis_test.go, grafana_prometheus_redis_dashboard_alias.json, main.go
It could be more friendly (especially in graph) to display the alias than just the node address. Add a modified dashboard for Grafana.
=> Add flag -redis.alias. Allow to give an alias to the redis node(s) address

build.sh, circle.yml
Sorry to bug you again @oliver006 - I downloaded your latest release v0.10.9 but it sadly still fails in my Docker container since the binary is still dynamically linked. I researched and experimented locally and found out that additionally the environment variable CGO_ENABLED=0 is needed. Running `file redis_exporter` should yield (note the **statically linked**):
```
redis_exporter: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, not stripped
```
I hope my provided patch for the circle.yml will let CircleCI build static binaries now.
=> Really make builds static

circle.yml, exporter/redis.go, exporter/redis_test.go
There were lots of changes I needed to make than I originally anticipated.
1. Created two new metrics: latency_spike_timestamp(when the latency spike last occured) and latency_spike_millisecond(how much the latency spike was when it last occured)
2. Updated extractInfoMetrics method to handle this new latency stats
Let me know if it looks good.
=> Added support to retrieve latency stats from redis nodes

README.md, main.go
This allows one to manage a file separately from the service definition
and simply restart the service once the configured file is updated.
=> [RDY] Support passing a file containing redis hosts

exporter/redis.go
=> exclude a metric if it contains a dash

.gitignore, exporter/redis.go, glide.lock, glide.yaml, main.go
Hi! The `github.com/Sirupsen/logrus` repo recently moved to `github/sirupsen/logrus` so this PR updates `redis_exporter` to use the new path and updates glide as well. Without this change, glide is unable to install its dependencies correctly because it can't find the `logrus` package. Specifically, it reports:
```
[ERROR] Update failed for github.com/Sirupsen/logrus: The Remote does not match the VCS endpoint
[ERROR] Failed to install: The Remote does not match the VCS endpoint
```
I also took the liberty of adding the `vendor` directory to `.gitignore`. Happy to revert if you feel it should be left out though. Thanks!
=> [glide] Update sirupsen dependency to use new path to repo

exporter/redis.go, exporter/redis_test.go
I would like to be able to monitor connected clients vs. the configured `maxclients` setting.
=> Add `maxclients` to config metrics

README.md, contrib/sample_collect_script.lua, exporter/redis.go, exporter/redis_test.go, main.go
Allow an optional Redis Lua script to collect extra metrics.
This can be enabled with a new `-script` flag. An example script is provided in contrib.
I needed a way to export metrics that are collected within a Redis hash and `-check-keys` does not support this. Adding support for [Redis Lua scripts](https://redis.io/commands/eval) allows a user to collect whatever metrics they want from Redis without writing a custom exporter.
The script metrics end up in a new `redis_script_value` vector.
=> Optional Redis Lua script for metric collection

exporter/redis.go
start_time is a more idiomatic way to store the process uptime,
and is what is provided by the Prometheus library itself.
Since this is a breaking change, I am happy to add this as a second
metric if necessary
=> Add start_time_seconds

contrib/grafana_prometheus_redis_dashboard.json, contrib/grafana_prometheus_redis_dashboard_alias.json
When viewing Grafana dashboards with large enough time ranges to include periods when Grafana `Pod`s have been restarted or deleted & re-created, Prometheus queries return multiple series (See screenshot)
The Grafana (>= 2.5) ["Singlestat" panel is designed only to handle single series](http://docs.grafana.org/features/panels/singlestat/#singlestat-panel), so returns a ["Multiple Series Error"](http://docs.grafana.org/features/panels/singlestat/#multiple-series-error) (see "before" Screenshot below) when viewed over time ranges where multiple Redis `Pod`s exist (`redis_exporter` metrics are tagged with multiple `instance=` names).
Due to the data types Prometheus returns for these queries, we can use a couple tricks to solve the problem (See "after" screenshot below).
Modifying the …
=> Grafana Dashboards: Fix "Multiple Series Error" with Redis uptime Singlestat panels

exporter/redis.go
Hello @oliver006 !
Thank you for this project. We've been using redis_exporter for over a year and it helps a lot.
I want to use these metrics in alerts rules:
* rdb_last_save_time
* rdb_last_bgsave_status
* aof_last_bgrewrite_status
* aof_last_write_status
Also I added other missed "persistence" metrics for consistency:
* rdb_bgsave_in_progress
* rdb_last_cow_size
* aof_last_cow_size
=> add all metrics from 'redis info' persistence section

exporter/redis.go
I'd like to extend list of AOF releated metrics. A server return few metrics if aof is disabled:
```
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0
```
but if AOF is enabled we get additional interesting metrics:
```
127.0.0.1:6379> CONFIG set appendonly yes
OK
--
aof_enabled:1
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:0
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:200704
aof_current_size:92
aof_base_size:92
aof_pending_rewrite:0
aof_buffer_length:0
aof_rewrite_buffer_length:0
aof_pending_bio_fsync:0
aof_delayed_fsync:0
```
In this PR I added the …
=> feat: add aof metrics

exporter/redis.go, exporter/redis_test.go
Remove `mem_fragmentation_ratio`:
* Comes from `redis_memory_used_rss_bytes / redis_memory_used_bytes`.
* Metric only provides 2 digits of accuracy compared to calculation.
Add allocator metrics.
Cleanup Prometheus naming of commands metrics names to avoid confusing
references to being a "Summary" metric, it's not.
Remove `total_system_memory`, this duplicates node_exporter metrics.
Signed-off-by: Ben Kochie <superq@gmail.com>
=> Cleanup some metrics

exporter/redis.go
As discussed in #228, added `total_system_memory_bytes` metric back.
=> Bring back total_system_memory_bytes metric.

Dockerfile
I'm running this in a kubernetes environment where there's a pod security policy disallowing the use of non-root images.
The industry recommendation is typically to run as a numbered user to avoid conflicts with actual host users.
This PR sets the user and group to `59000` to be able to run in those conditions.
=> Run as non-root user for secure environments

README.md, main.go
Signed-off-by: Javier J. Salmeron Garcia <jsalmeron@bitnami.com>
In some contexts, providing the password using REDIS_PASSWORD is not recommended, as this information could be potentially extracted by privileged containers that could execute commands like `docker inspect`. The same could be said to anyone that could access the kubelet host where the container is running. Because of this, some deployments require the ability to pass passwords as files. This PR enables this feature.
I set that REDIS_PASSWORD and REDIS_PASSWORD_FILE (the new variable that points to a file containing the password) to be mutually exclusive, so only one can be declared at the same time. This change does not break backwards compatibility.
=> Enable support for having the redis password in a file

exporter/redis.go, exporter/redis_test.go
Adding a new metric for measuring replication lag.
```
redis_connected_slave_lag_seconds{addr="**********",alias="",slave_ip="********",slave_port="6379",slave_state="online"} 1
```
=> Adding replication lag metric

.circleci/config.yml, exporter/redis.go, exporter/redis_test.go, main.go
[Tile38](https://github.com/tidwall/tile38) is a geospatial database that is using redis communication protocol and structure. I add a flag to support metric collection from tile38 databases. Tile38 offer a command named `Server` that is not available in `redis_exporter` and I add it with this PR.
=> Tile38 support

README.md, exporter/redis.go, exporter/redis_test.go
There are new key type in Redis 5 - Streams.
So, we get ability to monitor them.
=> Streams metrics support.

.gitignore, build-github-binaries.sh
* Use single gox command to parallelize build.
* Automatically package any archs gox spits out.
* Add sha256sums for packages.
=> Improve build script

exporter/redis.go
When running the redis exporter with redis 2.4 there's an error running the INFO command, since it doesn't accept the ALL parameter. The proposed fix is to run INFO without arguments if INFO ALL fails.
=> For redis 2.4 the INFO command should be passed without arguments.

README.md
Fix include-system-metrics env var name on Readme.
=> Fix include-system-metrics env var name on Readme

contrib/grafana_prometheus_redis_dashboard.json
This was lost in the 1.0.0 version when compared to `contrib/grafana_prometheus_redis_dashboard_exporter_version_0.3x.json`.
Thanks for an awesome exporter + dashboard :)
=> Make grafana dashboard import ask for datasource

README.md, exporter.go, exporter_test.go, main.go
I added a function to add CLIENT LIST stats that are group by client name in order to get a count of each client connected instead of just the total.
Please feel free to improve this push request and also please give me your opinion on how it can be improved in order to provide more labels to make this more flexible
=> Added client list details to use with PromQL

exporter.go, exporter_test.go
In 0.x versions, the duration of the most recent latency spike was expressed using the `latency_spike_milliseconds` metric. This metric name actually made a lot of sense when compared with the [Redis docs for these values](https://redis.io/topics/latency-monitor#latency-latest). In 1.x versions, this metric seems to have been replaced with a `latency_spike_timestamp_seconds` metric along with a transformation that is applied to the value to try to match the new unit.
The name of the new metric suggests to me that it might have been intended to be a replacement for `latency_spike_last` or something, but that it replaced the wrong metric. At any rate, this change adds the old metric (`latency_spike_milliseconds`) back in, and corrects the transformation for the existing metric to not …
=> Make latency spike duration metrics accurately reflect data

.drone.yml
To get the latest scratch image we can use the `latest` tag but we can't specify the latest Alpine based image without specifying an exact version for example `v1.2.1-alpine`, so I have added the `alpine` tag which serves the same purpose of `latest` but for Alpine based images.
=> Added alpine docker image tag

exporter.go
=> use promhttp.ContinueOnError to not fail on duplicate metrics

contrib/grafana_prometheus_redis_dashboard.json
The hover tooltip is wrong as it sums up every value which it shouldn't be doing if we want to see a real command call counts. The tooltip type should be set to "individual" to fix the value stacking/summing up issue.
Wrong tooltip:
Correct tooltip:
=> Fix command calls/sec grafana dashboard panel hover tooltip

exporter.go
When looking into #326 I noticed that not all calls to Redis are wrapped with doRedisCmd() and show up in the logs. This should address that.
=> always use doRedisCmd() to execute Redis commands

exporter.go
Metric names will be
- client_recent_max_output_buffer_bytes
- client_recent_max_input_buffer_bytes
Fixes #333
=> correctly pick up client_recent_max_input|output_buffer metrics

README.md, exporter.go, main.go
Google Cloud Memorystore for Redis blocks use of the CLIENT command.
https://cloud.google.com/memorystore/docs/redis/product-constraints#blocked_redis_commands
This causes an error to be logged with each scrape.
This flag provides the option to disable the `CLIENT SETNAME redis_exporter`
🙂
=> set-client-name flag

contrib/grafana_prometheus_redis_dashboard.json
Hello!
This PR adds panels for Average Time Spent by Command / sec, which takes the total time spent and divides it by the number of calls by command, as well as Total Time Spent by Command / sec, which calculates the  per second rate of total time by command. Furthermore the previously name Command Calls / sec panel is renamed to Total Commands / sec and its' stack graph which was previously cumulative is now individual which yields better results. Finally the dashboards tool tip has been changed to shared crosshair as to more easily correlate the various panels.
Please let me know what you think!
=> [dashboard] Add command related panels

README.md, contrib/grafana_prometheus_redis_dashboard.json
To view a redis cluster as a whole, the drop down is converted to a multi value. 
Hi @oliver006, this is a first pass, let me know what you think and if you are still on board with this change? 
As per above, opted for metrics by instance for the most part, but cannot quite get Connected/Blocked Clients nor Average Time Spent by Command panels to display ANYTHING. Thoughts?
fixes #352
Oh I also went and hid the legend for Total Commands up top as per our other convo.
=> [Dashboard] Refactor to allow viewing of multiples Redises (Redi?) simultaneously.

exporter.go
In redis 5.0, the commands stats info format is like this:
```
cmdstat_pexpire:calls=1120,usec=1438,usec_per_call=1.28,rt=0,max_rt=0,request_len=0,response_len=0,receives=0,qps=0
cmdstat_rpush:calls=715,usec=3577,usec_per_call=5.00,rt=0,max_rt=0,request_len=0,response_len=0,receives=715,qps=0
cmdstat_pexpireat:calls=107,usec=234,usec_per_call=2.19,rt=0,max_rt=0,request_len=0,response_len=0,receives=107,qps=0
cmdstat_select:calls=1685,usec=1245,usec_per_call=0.74,rt=0,max_rt=0,request_len=0,response_len=0,receives=1689,qps=0
cmdstat_lrange:calls=919,usec=1993,usec_per_call=2.17,rt=0,max_rt=0,request_len=0,response_len=0,receives=919,qps=0
cmdstat_info:calls=4057140,usec=166840049,usec_per_call=41.12,rt=40,max_rt=57,request_len=4,response_len=3178,receives=4057152,qps=14
...
```
There need …
=> fix commands stats in redis 5

README.md, exporter.go, main.go
Fixes #387
Added paramater REDIS_EXPORTER_TLS_CA_CERT_FILE --> Name of the CA certificate file (including full path) if the server requires TLS client authentication
=> Pass RootCAs to dialTLSConfig

.drone.yml, Makefile, contrib/docker-compose-for-tests.yml, exporter.go, exporter_test.go
Implements #405 
The division into three metrics (`sentinel_master_up`, `sentinel_master_sdown`, `sentinel_master_odown`) is deliberately done so that users have the opportunity to get both the master status _(up or not)_ and a specific state in case of an error: `sdown` or `odown`.
Info and descriptions from:
- https://redis.io/topics/sentinel
- https://github.com/redis/redis/blob/6.0/src/sentinel.c#L3406
=> Issue #405 | Add sentinel info metrics

contrib/k8s-redis-and-exporter-deployment.yaml
The example now should be simple apply, no need for local fixes.
=> fix k8s deployment example with proper api version and selector added

exporter_test.go, main.go
Before changes:
```
$ ./redis_exporter -count-keys "db0=xpto::*" -redis-only-metrics
flag provided but not defined: -count-keys
...
$ ./redis_exporter -help 2>&1 | grep count || echo "not found"
not found
```
After changes:
```
$ ./redis_exporter -count-keys "db0=xpto::*" -redis-only-metrics
INFO[0000] Redis Metrics Exporter     build date: 2020-10-23-19:34:19    sha1:     Go: go1.15.3    GOOS: linux    GOARCH: amd64
INFO[0000] Providing metrics at :9121/metrics
$ ./redis_exporter -help 2>&1 | grep count || echo "not found"
-count-keys string
Comma separated list of patterns to count, eg: 'db3=sessions:*'. Warning: The exporter runs SCAN to count the keys.
```
=> Add count-keys to the command line

contrib/redis-mixin/dashboards/redis-overview.json
This minor update fixes a bug where the datasource in a template variable was hard coded instead of using a variable. This means the variable will work when the datasource is not called `prometheus`.
=> update redis-mixin templated datasource to use templated variable

exporter/exporter.go, exporter/exporter_test.go
Add two metrics -
* sentinel_master_ok_sentinels
* sentinel_master_ok_slaves
Metric `sentinel_master_sentinels` and `sentinel_master_slaves` are
already added in #418 . But, they represent total number of sentinels and total
number of slaves sentinel instance has information about.
Added `sentinel_master_ok_sentinels` and `sentinel_master_ok_slaves` to
reflect `ok` or `working` sentinels and slaves count.
=> Add sentinel metrics

docker/Dockerfile.amd64, docker/Dockerfile.arm, docker/Dockerfile.arm64
Post merging of #435, drone docker releases are broken. Check https://cloud.drone.io/oliver006/redis_exporter/922/1/13 for reference. 
This commit fixes it.
=> Fix drone docker releases

.drone.yml, Makefile, README.md, contrib/docker-compose-for-tests.yml, exporter/exporter.go, exporter/exporter_test.go, main.go
when exporting the list of all clients, it greatly increases the label cardinality
plus a few other, minor things.
=> allow configuring whether to include the client port

README.md, exporter/exporter.go, exporter/key_groups.go, exporter/key_groups_test.go, main.go
Hello redis_exporter maintainer,
I am hoping to upstream an enhancement via this PR that I have been using for my local environments for tracking Redis memory usage by key groups as determined through a user-defined list of (LUA) regular expressions. I understand that such capability is available to some extent through the check-keys, check-single-keys, and count-keys parameters, so I have included a somewhat detailed explanation of how the enhancement work in the README which will hopefully convince the redis_exporter community that this is a useful enhancement to be incorporated into the official redis_exporter.
I have certainly enjoyed using redis_exporter, and I hope that I can give back a bit to the community through this PR.
=> Support for memory usage aggregation by key groups

README.md, contrib/collect_lists_length_growing.lua
Later we can create alerts or dashboards for this.
Specifically for old Redis versions < 3.1 where MEMORY commands are not available.
=> Collect length of redis lists growing up.

exporter/exporter_test.go, exporter/keys.go, exporter/keys_test.go
As discussed in #472 and #479, keys passed via check-single-keys are known in advance, so we can default to 0 if those keys are missing (as [suggested by Prometheus](https://prometheus.io/docs/practices/instrumentation/#avoid-missing-metrics)).
This PR does not add defaults for check-keys (as discussed in #479, this would add undesired additional overhead to redis_exporter).
=> Default to 0 when using check-single-keys

go.mod, go.sum
Reverts oliver006/redis_exporter#489
```
Stderr: exporter/clients.go:7:2: missing go.sum entry for module providing package github.com/gomodule/redigo/redis (imported by github.com/oliver006/redis_exporter/exporter); to add:
--
```
=> Revert "Bump github.com/gomodule/redigo from 1.8.3 to 1.8.4"

docker/Dockerfile.amd64, docker/Dockerfile.arm, docker/Dockerfile.arm64
I'v struggled with some issue to get the exporter running by the Helm chart. Pod Security Policy was created but enforced AppArmor profile will prefent the POD start:
```
Status:         Pending
Reason:         AppArmor
Message:        Cannot enforce AppArmor: AppArmor is not enabled on the host
```
The default PSP on my cluster doesn't allow to run root images. Normaly the is a USER defintion in the Dockerfile which is here only in the builder, but not the finally image. Added the USER definition there and got the exporter running.
=> Run Docker image as non-root

docker/Dockerfile.amd64
When golang resolves `localhost` on a system without a `/etc/nsswitch.conf` present it sends a request to the DNS server instead of using /etc/hosts to directly resolve it to `127.0.0.1`.
In our kubernetes cluster, we used the scratch image as a sidecar to redis, with the address `redis://localhost:6379`.
As the scratch container did not have a `/etc/nsswitch.conf` this generated a lot of DNS queries to localhost.
With this PR, the scratch image copies the /etc/nsswitch.conf file from the builder image. This setup should correctly resolve using the /etc/hosts file first, before doing a DNS query.
=> Copy /etc/nsswitch.conf to scratch docker image

exporter/exporter.go
in redis_sentinel version 3.0.7
redis_exporter cannot grab information on sentinel nodes
The debug mode shows that there is no info all command on sentinel of version 3.0.7 and no errors are reported.
So the infoall, err part of the code has no output
Modify the code judgment condition to make it use info conditional branch
redis_sentinel 版本3.0.7
redis_exporter不能在sentinel节点抓取信息
debug模式显示在3.0.7版本的sentinel上没有 info all命令并且无任何报错
所以代码中infoall,err部分无输出  
修改代码判断条件，使其能使用info条件分支
=> bug on redis_sentinel v3.0.7

.gitignore, Makefile, contrib/tls/gen-test-certs.sh, exporter/exporter.go, exporter/redis.go, exporter/tls.go, exporter/tls_test.go, main.go
This changes the handling of TLS cert files from pre-loading to lazy loading when `Prometheus` connects,
or when `redis_exporter` connects to a `Redis` instance.
This enables certificate rotation in systems that require increased security. A setup example would be to mount the cert-files into the `redis_exporter` container and let other systems update these files. The update process can run without involving `redis_exporter` and there is no need know when and why we need to restart the `redis_exporter` process for cert-reloading.
Previously the certs could expire in redis or redis-client and the only way to see this was that metrics was missing.
The scape interval is usually in seconds so I have not seen any significant  performance penalty for this, even with lower intervals.
Equivalent …
=> Add support for TLS certificate hot-reload

.drone.yml
Fails due to updtes to golangci-lint
https://cloud.drone.io/oliver006/redis_exporter/1192
This pins it to an older, working version. Will have to address the underlying issue at some later point.
=> pin golangci-lint docker image

exporter/keys.go
This adds a condition so that GET is only ran on types of keys that it works on - strings.
Before it was ran on every key and you could see errors with debug mode:
running command: GET [my-key]
WRONGTYPE Operation against a key holding the wrong kind of value
This also reduces the number commands ran on Redis from about 4 to 3 per key and should improve performance (unless all of your keys are strings).
I also thought of switching places of PFCOUNT and STRLEN which are ran on string types on the premise that regular strings are more common than HyperLogLog ones and STRLEN being the first conditional could slightly improve performance.
The problem is that STRLEN also works on HLL strings but returns the wrong (or at least not the one we want) value so I left it as is and added a comment …
=> Add condition to check if key is of type string before running GET to increase performance

contrib/redis-mixin/dashboards/redis-overview.json
This PR changes to using [$__rate_interval](https://grafana.com/blog/2020/09/28/new-in-grafana-7.2-__rate_interval-for-prometheus-rate-queries-that-just-work/) for promql queries containing a `rate` function call.
The hardcoded default of `1m` only works when the tsdb has data with a scrape interval of 15s or less. Some users may extend this to 30s or 60s in an effort to reduce time series data storage costs, which would render these queries ineffective.
A second commit on this PR also reduces the default timerange from 12h to 30m. This should help improve responsiveness of the first load, and reduce strain on the tsdb when the dashboard is used regularly.
=> Use $__rate_interval for rate queries in monitoring mixin

.github/workflows/codeql-analysis.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>
=> Set permissions for GitHub actions

contrib/redis-mixin/alerts/redis.libsonnet, contrib/redis-mixin/config.libsonnet, contrib/redis-mixin/rules/redis.libsonnet
Most mixins allow to customize selectors as such as seen in the Customising the mixin section in
https://monitoring.mixins.dev/
=> Allow the ability to customize redis exporter selector

.drone.yml, Makefile, contrib/docker-compose-for-tests.yml, exporter/exporter.go, exporter/info.go, exporter/info_test.go, exporter/metrics.go
As of Redis 7 ( specifically this PR https://github.com/redis/redis/pull/9462 ) it possible exporting the per-command percentile distribution via the `INFO LATENCYSTATS` subcommand or `INFO ALL`. ( percentile distribution is not mergeable between cluster nodes )
Here's a sample of INFO ALL ( focusing on commandstats and latencystats ):
```
(...)
cmdstat_rpop:calls=100000,usec=109759,usec_per_call=1.10,rejected_calls=0,failed_calls=0
cmdstat_set:calls=100000,usec=76770,usec_per_call=0.77,rejected_calls=0,failed_calls=0
cmdstat_zadd:calls=100000,usec=146737,usec_per_call=1.47,rejected_calls=0,failed_calls=0
cmdstat_mset:calls=100000,usec=381537,usec_per_call=3.82,rejected_calls=0,failed_calls=0
cmdstat_lpop:calls=100000,usec=130932,usec_per_call=1.31,rejected_calls=0,failed_calls=0 …
```
=> Added latency_percentiles_usec summary (A summary of latency percentile distribution per command)

exporter/info_test.go
This PR fixes an added issue on https://github.com/oliver006/redis_exporter/pull/652#issuecomment-1141097840. 
check of failure
```
$ TEST_REDIS7_URI=redis://127.0.0.1:6379 go test exporter/*.go --test.run TestLatencyStats* -test.v
=== RUN   TestLatencyStats
info_test.go:135: didn't find aalatency_percentiles_usec
--- FAIL: TestLatencyStats (0.06s)
FAIL
FAIL    command-line-arguments  0.067s
FAIL
```
check of fix:
```
$ TEST_REDIS7_URI=redis://127.0.0.1:6379 go test exporter/*.go --test.run TestLatencyStats* -test.v
=== RUN   TestLatencyStats
--- PASS: TestLatencyStats (0.06s)
PASS
ok      command-line-arguments  0.061s
```
=> fixed TestLatencyStats() wrong check

contrib/redis-mixin/README.md
Replace deprecated `go get` by `go install`.
=> docs: add redis-mixin build instructions for go >= 1.17

exporter/exporter.go
When `scrapeRedisHost` fails to connect to a Redis instance, the code now tries to redact the password of the Redis address (URL).  If it can parse and redact it, it will print the address in the error message.   Otherwise, we note that `-debug` is needed to see the address.   It does not log any URL parsing errors, just in case that may leak any info.
Testing:
```
> ./redis_exporter  -redis.addr "redis://user:peace@foobar.com:9999"
INFO[0000] Redis Metrics Exporter <<< filled in by build >>>    build date: <<< filled in by build >>>    sha1: <<< filled in by build >>>    Go: go1.18.1    GOOS: darwin    GOARCH: arm64 
INFO[0000] Providing metrics at :9121/metrics           
ERRO[0018] Couldn't connect to redis instance (redis://user:xxxxx@foobar.com:9999)
```
=> Add redacted addr to scrapeRedisHost error message (#638)

contrib/redis-mixin/alerts/redis.libsonnet
Thanks for exporter and mixin. Was looking that mixin does not have redis_cluster metrics. 
Want to update to have cluster state as well as slot/pslot fail alerts.
Do let me know if any modifications are needed to get this Merged. 
Thanks
=> updating to add redis cluster alerts to redis mixin

exporter/exporter.go, exporter/sentinels.go, exporter/sentinels_test.go
Expose new metrics for Redis Sentinel from command `SENTINEL CKQUORUM <master-name>`
=> feat: add Redis Sentinel metrics ckquorum

exporter/info.go
Add support for info keys like master_[0-9]_ which are produced by keydb in case there are more than 1 master.
```
redis_master_link_up{master_host="m0.server.local",master_port="6377"} 1
redis_master_link_up{master_host="m1.server.local",master_port="6377"} 1
```
=> keydb multimaster support

exporter/exporter.go, exporter/http_test.go, exporter/lua.go, exporter/lua_test.go, exporter/pwd_file_test.go, main.go
No breaking changes, the same option and env var supports now multiple Lua scripts separated by comma
Closes #699
=> Feature: Add support for multiple lua scripts evaluation

contrib/k8s-redis-and-exporter-deployment.yaml
I suggest adding security context to the Kubernetes example. It will allow users to easier find the required user/group and more securely and deploy this exporter into their clusters.
I tested this securityContext in my deployment. All works fine
=> Add securityContext to kubernetes example for

README.md
Hi!
The old link 404'd. I swapped it with a new one that fixes the issue. It's the same dashboard ID (763).
The new link: https://grafana.com/grafana/dashboards/763-redis-dashboard-for-prometheus-redis-exporter-1-x/
Fixes #745
=> Dead grafana dashboard link fixed.

exporter/clients.go, exporter/clients_test.go, exporter/exporter.go, exporter/exporter_test.go, main.go
Related to issue #775, redis_connected_clients_details don't show user info.
This is still a WIP as there are no test yet. But it tries to follow [comment](https://github.com/oliver006/redis_exporter/issues/775#issuecomment-1461222214)
Please let me know if this approach and code changes are likely to be merged, and I will finish it. Otherwise feel free to reject it.
_parseClientListString_ now returns a map containing the parsed output of the client list reply
_extractConnectedClientMetrics_ now creates the metric description. Instead during startup at _exporter.go_
Maybe this is not somehow very efficient as they are created at every scrape.
=> include user info in redis_connected_clients_details

exporter/redis.go
=> fix: support tls for cluster refresh op

exporter/exporter.go, exporter/http.go, exporter/http_test.go, exporter/pwd_file.go, main.go
1. add redis.password-file hot reload via `/-/reload`#727
2. fix a typo which log `level=error msg="Loaded 3 entries from ./redis-pwd-file.json"`
3. change `redis.addr` default "",explain this,when I use `redis.password-file` most time ,I don not need a `redis.addr`,so this will make continuously outputted logs `level=error msg="Couldn't connect to redis instance (redis://localhost:6379)"` disappear
=> feat: Add redis.password-file hot reload via `/-/reload`

exporter/exporter.go
Adding gauge metric for `pubsubshard_channels`
> pubsubshard_channels: Global number of pub/sub shard channels with client subscriptions. Added in Redis 7.0.3
=> Add metric for pubsubshard_channels

.drone.yml, Makefile, contrib/docker-compose-for-tests.yml, exporter/redis.go, exporter/redis_test.go
This PR is to fix the bug when using password file with `isCluster` mode.
This issue #835
=> Fix cluster refresh failed  when using pasword file with isCluster mode

README.md
Fixes the example ACL SETUSER command, issue #851.
=> fix: removed space before password

exporter/key_groups.go
This fix avoid an exception to bee thrown so scrapping fail for redis version < 4.0
Metrics will so only contains keys_group_count and not memory_usage 
Tested on docker redis 3.2.4: (docker pull r900/redis:3.2.4)
=> fix scrapping for redis < 4.0

exporter/tls.go, exporter/tls_test.go
Previously a server CA had to be specified for TLS work, even if the system store trusted the cert already.
=> Add support for loading TLS system certificate store

exporter/clients.go, exporter/clients_test.go
This PR addresses issue #863. `parseClientListString` is updated to parse IPv6 addresses.
=> update client info parsing to accept IPv6 addr

main.go
=> Add graceful shutdown

Makefile
Since Docker Compose is installed as a plugin in v2 the binary `docker-compose` is not always available.
The makefile will now use `docker compose` in that case.
The [recommendation](https://docs.docker.com/compose/migrate/#docker-compose-vs-docker-compose) is to start using the command `docker compose` instead of `docker-compose`, so an alternative is to replace, but this gives somewhat smoother migration.
=> Support Docker Compose V2 in Makefile

exporter/streams.go, exporter/streams_test.go
The entry id in different versions of redis is not always in the 17th and 19th positions of the `xinfo stream`.
In 6.x and 5.x, `first-entry` is 11th, `last-entry` is 13th
=> fix: compatible with stream entry id metric for redis version 6.x/5.x.

docker/Dockerfile
resolves CVE-2023-42365 found in
alpine://3.20:busybox-binsh:1.36.1-r28
alpine://3.20:ssl_client:1.36.1-r28
alpine://3.20:busybox:1.36.1-r28
=> Bump alpine to 3.20.1 to fix CVEs

exporter/metrics.go
if parse value err, means the value is not float. So there may be something bad happened. If we dont't return, the metric value is 0, which may has a different meaning with the real value. From the code above, `0` also means `fail`, `err` and `false`.
=> fix: stop return metrics when parse float value err

exporter/exporter.go, exporter/exporter_test.go
Fixes #932
Exports configured `client-output-buffer-limit` as a metric. Combined with `mem_total_replication_buffers` it will allow you to alert on when replication buffers are reaching the limit.
```
(mem_total_replication_buffers / config_client_output_buffer_limit_bytes{class="slave", limit="hard"}) > 0.7
```
Happy for suggestions on alternative metric name and labelling tactic.
=> feat: export client-output-buffer-limit

exporter/exporter.go, exporter/info.go
metrics output
```
redis_instance_info{master_replid="08d93f3f012d5c31fc135f81eebe34056a16718b",maxmemory_policy="noeviction",os="Linux 6.8.11-300.fc40.aarch64 aarch64",process_id="1",redis_build_id="f52510608ef57ee1",redis_mode="standalone",redis_version="6.2.6",role="master",run_id="5df26f6efeab16c5eed4f8198f431559f510ccfc",tcp_port="6379"} 1
```
related issue: #919 
only add label `master_replid` to metric`instance_info`, replication metrics hasn't add this label. Will add later
=> feat: add label `master_replid` to metric`instance_info`

contrib/grafana_prometheus_redis_dashboard.json
Add a datasource variable into the grafana dashboard template. This makes the dashboard suitable for provisioning.
[More info about dashboard provisioning](https://grafana.com/docs/grafana/latest/administration/provisioning/#dashboards)
=> Make the grafana dashboard provisionable

exporter/exporter.go, exporter/modules_test.go
According to my tests with real workload, this metric type is counter, I'm renaming it according to Prometheus recommendations and moving to `metricMapCounters` map.
=> Hotfix: Fix search_total_indexing_time metric type

exporter/exporter.go
GCP Redis does not support the config command, making it impossible to retrieve maxclients. It needs to be extracted from info all
=> maxclients extracted info all

exporter/exporter_test.go, exporter/http_test.go, exporter/key_groups_test.go, exporter/keys.go, exporter/keys_test.go, exporter/latency_test.go, exporter/redis.go, exporter/sentinels.go, exporter/slowlog_test.go, exporter/streams_test.go
=> improve latency by running "SELECT" only if the db is different

exporter/exporter.go, exporter/exporter_test.go, exporter/http_test.go, exporter/info.go, exporter/info_test.go, exporter/key_groups_test.go, exporter/keys.go, exporter/keys_test.go, exporter/lua_test.go, exporter/redis_test.go, exporter/streams_test.go, main.go
can help with reducing load on master nodes - see #931
=> Add flag to skip checkKeys if role == master

exporter/http.go
Previously, the error message for RedisExporter initialization was hardcoded and didn't include the actual error details. This commit modifies the error response to include the dynamic error value using fmt.Sprintf(), making debugging easier.
=> fix(exporter): improve error message in HTTP handler

Makefile, docker-compose.yml, exporter/redis_test.go
remove bitname redis-cluster image, use oliver006/ valkey-cluster-password instead
bitnami is planning to remove their docker images or make them for-pay
see: 
https://community.broadcom.com/tanzu/blogs/beltran-rueda-borrego/2025/08/18/how-to-prepare-for-the-bitnami-changes-coming-soon
one down, one to go
=> remove bitname redis-cluster image

Makefile, docker-compose.yml, exporter/sentinels_test.go
remove bitname redis-sentinel image, use vanilla valkey image instead
bitnami is planning to remove their docker images or make them for-pay
see:
https://community.broadcom.com/tanzu/blogs/beltran-rueda-borrego/2025/08/18/how-to-prepare-for-the-bitnami-changes-coming-soon
=> replace bitnami/valkey-sentinel docker image
