README.md, circle.yml, exporter/redis.go, exporter/redis_test.go, main.go
=> Allow for unix socket addresses and export cluster stats

exporter/redis.go
=> Continue even if CONFIG fails (for AWS ElastiCache)

circle.yml
=> use zip instead of tar for windows releases

Dockerfile, circle.yml
And then COPY it into the image.
=> build binary for docker in circleCI with proper ldflags

exporter/redis.go
=> add "addr" to check key metrics

build.sh, circle.yml
=> Make builds extra static, bump golang version to 1.8

circle.yml, exporter/redis.go, main.go
Addresses the max_memory issue mention in #13
=> Get maxmemory from INFO command

exporter/redis.go
=> Add network timeouts

exporter/redis.go, exporter/redis_test.go
My first lines in golang... please be patient ;)
=> --check-keys could use wildcards to search existing keys

exporter/redis.go, exporter/redis_test.go, glide.lock
fyi @azr - there was a bug in #94 - this should fix it.
=> fix sanitizeMetricName()

exporter/redis.go, exporter/redis_test.go
=> Reset keySizes and keyValues GaugeVec before scraping to remove old data

exporter/redis.go
This PR adds a `replication` metric, this is useful in cluster setups were you need to find the master node or some slave information.
Example:
```
redis_replication{master_host="10.91.64.152",master_link_status="up",master_port="6379",role="slave",slave_read_only="1"} 1
```
=> Add replication metric

main.go
Added support for exporting Redis only metrics if required. Default behavior is same as existing behavior, i.e., all Redis metrics including metrics for go runtime and go http handlers are exported. If the exporter is run with "-redis-only-metrics true", then only Redis specific metrices are exported.
=> Changes for exporting redis only metrics if needed

exporter/redis.go, exporter/redis_test.go
Expose offset of connected slaves, useful to monitor replication lags
=> Add slave offset metrics

exporter/redis.go
=> on CONFIG error log Debugf() only

exporter/redis.go
For issue https://github.com/oliver006/redis_exporter/issues/138
=> set default db_keys & db_keys_expiring value to 0 for all available databases

exporter/redis.go, exporter/redis_test.go
=> only pad db key counts when running extractInfoMetrics() the first time

exporter/redis.go
=> Fix dbCount in cluster mode

exporter/discovery.go
=> Add alternative credentials claim for host.

exporter/redis.go, exporter/redis_test.go
=> Properly decode uptime from redis

exporter/redis.go
=> Add total_system_memory

contrib/grafana_prometheus_redis_dashboard.json, contrib/grafana_prometheus_redis_dashboard_alias.json
=> fix query in dashboard

exporter/redis.go
=> treat string "err" as failure and return zero for gauge

Dockerfile, README.md, build.sh
The rationale is to provide a minimal and secure image.
It is pretty common to use the `scratch` base image in case of static binaries, look [here](https://github.com/coredns/coredns/blob/c8f0e94026b5f3530064dd3266eef1a80e3b0f1c/Dockerfile#L6) for instance. It is secure and small.
```sh
$ docker images
REPOSITORY                  TAG        IMAGE ID        CREATED              SIZE
oliver006/redis_exporter    scratch    16282df0c5a4    About an hour ago    6.59MB
oliver006/redis_exporter    latest     5eccae8509db    12 days ago          19.6MB
```
Stripping go binaries talks for itself:
```sh
~/g/s/gi/o/redis_exporter (shrink-binary-and-image) $ ls -lh dist
total 40008
-rw-r--r--  1 nicorevin  staff   2.4M Dec 15 22:22 redis_exporter-.darwin-386.tar.gz
-rw-r--r--  1 nicorevin  staff …
```
=> Shrink binary and image

exporter/redis.go
My suggestion to fix issue #221.
=> fixed issue#221: apply correct key name while formatting debug log

exporter/redis.go
I'm not sure if you were not logging the error intentionally, but it'd be nice if it could be logged.
=> log the error from scanForKeys

exporter/redis.go
add last_slow_execution_duration_seconds
=> add last_slow_execution_duration_seconds

exporter/redis.go, exporter/redis_test.go
=> Split key-value line on first colon

main.go
=> trim white space from redis pwd file contents

.drone.yml, contrib/docker-compose-for-tests.yml, exporter.go, exporter_test.go
=> remove global variables, fix metrics map race condition

README.md
Hello @oliver006 ,
Very good project. It's help me every day on the troubleshooting Redis nodes, thanks for the project.
I'm suggesting just a few adjustments on the README, as we quickly chat about on https://github.com/mtulio/redis_exporter/pull/1
=> chore: update README sections (#1)

main.go
=> fix default addr, make it default to redis://lcoalhost:6379

exporter.go, exporter_test.go
=> prefix Tile38 metrics with tile38_ and correctly parse true and false

.drone.yml, README.md, build-github-binaries.sh, exporter.go, exporter_test.go, main.go
Fixes #282, #298, and #301 plus misc cleanup.
=> A couple of smaller changes and fixes

.drone.yml, exporter.go, exporter_test.go
=> fix handling of IP addresses in /scrape endpoint, add tests, add client name

.drone.yml, Dockerfile, main.go
Trying to address the issue raised in #312
=> ARM docker builds

exporter.go
=> don't panic on error for NewConstMetric(), catch it and continue

exporter.go, exporter_test.go
=> add health endpoint

exporter.go
the `latency latest` redis command can return multiple results:
```
127.0.0.1:6379> latency latest
1) 1) "fork"
2) (integer) 1582137796
3) (integer) 244
4) (integer) 318
2) 1) "expire-cycle"
2) (integer) 1582134822
3) (integer) 8
4) (integer) 181
3) 1) "fast-command"
2) (integer) 1582137383
3) (integer) 58
4) (integer) 567
4) 1) "command"
2) (integer) 1582137381
3) (integer) 231
4) (integer) 1230
```
But the current redis_exporter code was only showing metrics on the first element of that list.
```
$ curl --silent localhost:9101/metrics | grep ^redis_latency
redis_latency_spike_duration_seconds{event_name="fork"} 0.244
redis_latency_spike_last{event_name="fork"} 1.582137796e+09
```
This change iterates that list and returns all the elements:
```
$ curl --silent localhost:9101/metrics | …
```
=> loop latency results

build-github-binaries.sh, docker/Dockerfile.arm
=> Fix arm builds, no parallel binary asset uploads to github

exporter.go, exporter_test.go
fixes https://github.com/oliver006/redis_exporter/issues/404
fixes https://github.com/oliver006/redis_exporter/issues/403
=> Add maxmemory_policy and memory reservation metrics

exporter.go
- Add output buffer memory usage in client details report
=> Add output buffer memory usage in client details

Makefile
=> Fix CGO_ENABLED flag

.drone.yml
=> add docker dry run to tests

exporter/exporter_test.go, exporter/keys.go, exporter/lua.go, exporter/lua_test.go, exporter/pwd_file.go
=> Add some addtl logging

contrib/redis-mixin/alerts/redis.libsonnet, contrib/redis-mixin/config.libsonnet, contrib/redis-mixin/mixin.libsonnet
Allow mixin users more flexibility to set the threshold
=> Make the redis connection threshold a variable for alerting

exporter/exporter.go
Main thread cpu time was added in 6.2
https://raw.githubusercontent.com/antirez/redis/6.2/00-RELEASENOTES
=> Add main_thread metrics added in 6.2

exporter/exporter.go
=> Add new metrics of info cmd to redis exporter

exporter/exporter.go
Hello,
I've got the error - `Redis CONFIG err: redigo: unexpected element type for Strings, got type []interface {}`
It can be noticed only in `-debug` mode.
KeyDB returns `tls-allowlist` array value in CONFIG GET request.
And redis_exporter silently does not set any `redis_config_$key` metrics, which affect the prometheus alerts (they do not work). 
Can we skip non-string keys in config-metrics?
Thank you.
=> check redis config values, and skip non string replies.

exporter/exporter.go, exporter/keys.go, exporter/keys_test.go, main.go
backwards compatible version of https://github.com/oliver006/redis_exporter/pull/806
=> feat: add option to disable exporting values of keys

exporter/exporter_test.go, exporter/keys_test.go, exporter/metrics.go, exporter/streams.go, exporter/streams_test.go
=> Fix stream info retrieval

README.md
=> fix: add and update documentation about acl usage

contrib/grafana_prometheus_redis_dashboard.json
=> Change total item per DB panel unit to short

.github/workflows/tests.yml, Makefile, docker-compose.yml, exporter/exporter.go, exporter/exporter_test.go, exporter/http_test.go, exporter/redis.go, exporter/redis_test.go, exporter/streams_test.go, exporter/tls_test.go
=> support valkey:// and valkeys:// scheme

README.md
=> Fix: Update CI badge in readme to GH Actions

exporter/sentinels.go
=> fix sentinel_master_setting_ckquorum

.github/workflows/tests.yml, README.md, contrib/sample-pwd-file.json, docker-compose.yml, exporter/exporter_test.go, exporter/http.go, exporter/pwd_file_test.go, exporter/redis.go
=> Support usernames in password file

README.md, exporter/exporter.go, exporter/http.go, exporter/http_test.go, exporter/nodes.go, exporter/nodes_test.go
Add discovery endpoint that can be used to discover all nodes in a Redis cluster.
=> Add discovery endpoint for Redis cluster

Makefile, docker-compose.yml, exporter/exporter.go, exporter/http_test.go, exporter/modules_test.go
* Add support for v8.0 search module metrics
* Add Redis v8.0 to test suite
* Add tests for RediSearch v8 metrics
* Fix trailing spaces in docker-compose.yml
fixes #1004
=> Feature: Add support for v8.0 search module metrics

exporter/exporter.go, exporter/keys.go, exporter/keys_test.go
=> Fix processing of check-keys

.gitignore, exporter/clients_test.go, exporter/exporter.go, exporter/exporter_test.go, exporter/http.go, exporter/http_test.go, exporter/info_test.go, exporter/keys.go, exporter/keys_test.go, exporter/lua_test.go, exporter/pwd_file_test.go, exporter/redis_test.go, exporter/sentinels_test.go, exporter/streams_test.go
=> Use cluster mode, in all the places

Dockerfile
It will address potential CVEs that come from the 3.21 OS.
=> Bump Alpine distro to 3.22
